### ISSUE TITLE
Flag to ignore a check

### ISSUE THREAD

**Issue by CashWilliams** [seanhamlin/site-audit#149]
Would be nice to have a flag to ignore a check.

Use case -

- An auditor reviews a site with a predetermined profile.
- Auditor reviews report and decides one of the findings is not applicable in this particular case.
- Auditor reruns with an ignore flag to move that check to the bottom of the report (without reporting it as an error)

I'd think this wouldn't completely remove the check from the report, but rather just grey it out, not counting the either the pass or fail. The results would still be displayed.

**Comment by seanhamlin** [comment]
@CashWilliams I am assuming that it would not make sense in this particular situation to create a custom profile for the site? This type of data (e.g. what policies run, what order, and what options they run with) are typically driven out of a profile.

**Comment by fiasco** [comment]
One option could be to break the profile down into component profiles then combine them to produce relevant audits for the targets opposed to a generic all-in-one profile.

We consider options like `--ignore-errors`, `--ignore-not-applicable` and `--ignore-warnings` etc but then we also have to build in feature parody for multisite and site-factory which is not ideal.

Ignoring policies specifically may conflict with the policy dependency tree also.

Features like this essentially allow you to hide the fact a site doesn't pass a profile which in some cases would question the integrity of the tool.

There is a feature when writing an Audit called [prerequisites](http://drutiny.readthedocs.io/en/latest/audits/#audit-prerequisites) which allows you to run checks before running the audit allowing the audit to make itself not applicable instead of erroring in the audit. 

Finally, a recent change to the 2.x branch allows a profile to determine how to render the HTML report in which case it can choose to omit errors. I like this approach most as its specific to the nature of the profile opposed to the nature of the tool.

**Comment by fiasco** [comment]
`2.1.x` now has the `--exclude-policy` option on `profile:run` which will allow you to remove policies not applicable to a site.
