### ISSUE TITLE
minimum-stability needs documenting

### ISSUE THREAD

**Issue by seanhamlin** [seanhamlin/site-audit#173]
I believe that this is required to be set to `dev` in your root `composer.json` in order to require the various plugins that exist for Drutiny. We should document this.

**Comment by fiasco** [comment]
In order to produce 2.1.x I needed to tag all the libraries so that there was a stable build point for 2.0.x. So you can technically build a stable build today of Drutiny without a `minimum-stability: dev` setting (I think, I could be wrong). But it would be on 2.0.1 I think.

In order to truly move away from a dev minimum stability, we need to identify a proper tagging system to ensure all libraries have available stable releases for the current head branch (2.1.x).

Inside the plugin libraries I've started setting the require version of `drutiny/drutiny` to `2.1.*@dev` which allows them to use stable versions of `2.1.x` or dev if the minimum-stability allows it.

**Comment by seanhamlin** [comment]
I just did a fresh `2.1.1` install with Adama, and it was fine right up until we wanted to include `drutiny/acquia`, it bombed out when running that command, due to that plugin requiring dev dependencies which were not allowed by the root `composer.json`. A simple docs fix sounds appropriate.

**Comment by fiasco** [comment]
I can replicate but this is technically an issue with `drutiny/acquia` not having a stable release for the `2.1.x` branch. So this should be tracked over there since `drutiny/drutiny` does have stable releases in 2.1.x and 2.0.x.

Also, drutiny/acquia does document that its minimum-stability is dev.
