### ISSUE TITLE
Markdown template tables lose formatting

### ISSUE THREAD

**Issue by shanefjordan** [seanhamlin/site-audit#180]
The markdown templates for the severity statistics, summary, and appendix summary lose the formatting.

These tables should be wrapped in a code markdown tag to allow the formatting for the table spacing to work properly.

**Comment by fiasco** [comment]
@shanefjordan can you please provide examples of what you get at the moment? 

Since column width can't be predicted due to the mustache template rendering, I recently wrote a table formatter for Markdown to make sure the tables were re-adjusted so in plain text, they still looked ok: https://github.com/drutiny/drutiny/blob/2.1.x/src/Report/Format/Markdown.php#L139 

If we wrap these tables in preformatting then they won't render into HTML in the HTML format output which defeats the point of using markdown.

**Comment by shanefjordan** [comment]
@fiasco The column width adjustments you made appear to work great when viewing it in the terminal. However, when adding the markdown to ZenDesk all spacing is then lost. 

This example shows the output when wrapping with the preformat: https://drive.google.com/open?id=1vosUi4ryJRErRMWmfJbxftzyHXsZvDkH

This example shows the output when not wrapping n the preformat: https://drive.google.com/open?id=1k9lsmUtb5FCfCxuRNVBlO94GBm63_Faw

The HTML and markdown formats each use separate template files. Are you saying that by adding the preformat tags to the markdown template file that this will also affect the HTML template?

**Comment by fiasco** [comment]
ok I see Zendesk doesn't support tables in Markdown: https://support.zendesk.com/hc/en-us/articles/203691016-Formatting-text-with-Markdown. So the best option would be to pre-format the table to retain the formatting. This however, wouldn't be a sensible decision to make in the Markdown Format since it doesn't follow the Markdown convention.

> The HTML and markdown formats each use separate template files. Are you saying that by adding the pre-format tags to the markdown template file that this will also affect the HTML template?

Yes, the HTML Format class extends the Markdown one.

I think the best option here would be to add a zendesk formatter that simply extends the Markdown Format and adds the pre-formatting around the table.

**Comment by fiasco** [comment]
Core now supports the ability for formatters to be plugged in via other extensions. I don't think it makes sense for Drutiny to write and maintain zendesk integration at this stage but feel free to write your own.

To implemented a zendesk format, I suggest you do the following:

1. Create a class that extends `Drutiny\Report\Format\Markdown` called Zendesk
2. Copy and paste the `formatTables` static method into the Zendesk class
3. Where the method identifies the start and stop of a table, ensure the markdown back ticks are placed to ensure the pre-formatting occurs
4. Add the new class to your `drutiny.config.yml` file under the `Format` key.

Example drutingy.config.yml:
```
Format:
  zendesk: Drutiny\<my_custom_namespace>\Format\Zendesk
```
