### ISSUE TITLE
Data in html tables sometimes overflows table cells

### ISSUE THREAD

**Issue by scottreese** [seanhamlin/site-audit#202]
Whenever I run a policy which includes data in a table and specify the format as html, there are invariably some cells which have data that overflows the defined table dimensions. I usually fix this by adding `table-layout: fixed` to the CSS for the `table` element in the generated html or via the inspector in chrome dev tools before printing to PDF. I wanted to investigate the possibility of getting this added as part of the generated html/CSS.

**Comment by bschilt** [comment]
@scottreese Is this primarily a concern for printed reports? Adding `table-layout: fixed` to the table element does resolve the text overlapping issue, but it, in turn, makes all columns evenly spaced. Here is a nicely formatted table for reference:
![traffic_analysis_-_www_anl_gov](https://user-images.githubusercontent.com/332185/49758361-f9631f80-fc7b-11e8-914b-19af41bd7164.png)

When I add `table-layout: fixed` it looks like this, notice the columns are evenly spaced:
![traffic_analysis_-_www_anl_gov](https://user-images.githubusercontent.com/332185/49758445-316a6280-fc7c-11e8-8168-cf6005beffb9.png)

However, the cells that had an excessive amount of characters does get wrapped which makes the printed report and HTML report more usable. 
![traffic_analysis_-_www_anl_gov](https://user-images.githubusercontent.com/332185/49759382-c0787a00-fc7e-11e8-83a0-6d0e724961e9.png)

I have looked into the issue and one of the headaches is that some of the long URLs don't contain "breakable" characters, according to CSS rules and there currently is no way to specify a custom list of word break characters. 

I do think it makes sens to add `table-layout: fixed` to the print style sheet since without it, tables with long text become unusable.

**Comment by scottreese** [comment]
@bschilt yes, this was specifically a concern when printing reports to share with customers so I think adding `table-layout: fixed` to the print stylesheet would do the trick.

**Comment by bschilt** [comment]
This issue has been fixed in Acquia's default theme. The core Drutiny theme will not be updated with this fix since there is no custom css being used, it's all default bootstrap templates. A custom theme would need to be created to apply any customizations to the layout.
