### ISSUE TITLE
[Help] "composer require drutiny/drutiny 2.3.*@dev --dev" not working

### ISSUE THREAD

**Issue by joshirohit100** [seanhamlin/site-audit#229]
Unable to add this via composer. Running `composer require drutiny/drutiny 2.3.*@dev --dev` giving error -
`zsh: no matches found: 2.3.*@dev`

**Comment by fiasco** [comment]
Is that a zsh issue? I think composer is a bit more verbose in its output.

**Comment by joshirohit100** [comment]
Nope! composer not giving any other information regarding the error and only `zsh: no matches found: 2.3.*@dev`

**Comment by fiasco** [comment]
Based on your output though, its ZSH thats complaining? 
Do you get the same issue when using bash?

Also, if you're using `--dev` because you're trying to add drutiny to your Drupal project, I'd strongly advise against it. I don't think the symfony frameworks are compatible. You're better off using Drutiny in isolation.
