### ISSUE TITLE
Version 2 rewrite

### ISSUE THREAD

**Issue by seanhamlin** [seanhamlin/site-audit#93]
@fiasco has started a v2 branch https://github.com/seanhamlin/drutiny/compare/master...fiasco:2.x

Key new features:
* Checks have defined options now, complete with validation and default values. This helps to make this explicit, so things like profile builders could ask questions in the future.
* Driver plugins - the ability to execute the check via a plugin system
* Sandbox class, instead of Context
* New console commands, check:run etc
* Progress bar on CLI

Still needs discussion:
* **Removing the annotation from the check class**, I was quite a fan of this as it kept the checks self contained. Drutiny in the early days actually had separate YAML files, and it was hard to keep the YAML and the check together, and made PRs harder to review. Essentially the crux of this issue is having multi line annotation strings.
* **Validation of the check at runtime vs TravisCI time**, I personally prefer TravisCI to do this checking.

Still needs to be done:
* Caching of drush commands (e.g. variable-get)
* Porting of all the checks over
* Porting of the profiles
* Moving the namespace of checks out of a D7 and D8 folder structure and into the types of checks they are, e.g. 'security', 'performance', 'bestpractice'
* port the phpunit tests over
* Removal of settings based checks, and only support the check classes (as they contain additional metadata)
* Drupal multisite and ACSF running

**Comment by fiasco** [comment]
#94 for the issues still needing discussion

**Comment by fiasco** [comment]
> Moving the namespace of checks out of a D7 and D8 folder structure and into the types of checks they are, e.g. 'security', 'performance', 'bestpractice'

@seanhamlin do you have a sense of how that should work? I see two problems to solve:
* What is the filepath for the same check but against different compatibilities? E.g. CSS Preprocessing for D7 and D8
* What if a check is both best practice and performance or performance and security? Which path should it take and why?

Is this more about having the ability to categorize checks better or about namespace conventions?

**Comment by seanhamlin** [comment]
Yes, this is more about Check categorisation, and removing the weirdness that will occur when Drupal 9 comes out (as I would imagine a lot, if not all of the Drupal 8 checks will work exactly the same). When I discussed this with @steveworley, the idea of a Check having requirements would be nice, e.g.

```
requires :
  - drupal8
  - drupal9
  - linuxhosting
```

Or something like that. I still think it is valuable to split the Drupal 7 checks from the Drupal 8 checks, as the some of the strings do differ between them.

What I had in my head for folder structure

```
src/
  Check/
    Performance/
      d7.preprocess.css.php
      d8.preprocess.css.php
    BestPractice/
    Security/
```

**Comment by fiasco** [comment]
> d7.preprocess.css.php

How can this work with PSR standard naming conventions of PHP files? Wouldn't it need to be `D8PreprocessCssCheck.php`?

```
requires :
  - drupal8
  - drupal9
```

**requires** is probably the wrong key here since you cannot require both drupal8 and drupal9 and your validation framework needs to understand if its an AND or OR condition to satisfy.

PHP interfaces are perhaps a better approach for define check **compatibility**:

```php
class CSSPreprocessCheck implements Drupal8CheckInterface, Drupal9CheckInterface {
```

while PHP traits are useful for validating **dependencies**

```php
class CSSPreprocessCheck {
   use Drupal8Or9CheckContstraint;
   use UnixCheckConstraint;
```

Both approaches would be better than specifying these things in YAML then having to validate without PHP defined mechanisms to do so (Refection++).

Categorisation however, is something that suits YAML well:

```yaml
categories:
  - performance
  - best practice
```

This could be used to help drive console `check:list` filters and grouping. Once in yaml, its also worth asking if its necessary to have it reflected in the filesystem and PHP namespace? 

Personally, for PHP namespaces and therefore file directory organisation, I like top-level terms like `Drupal`, `Platform`, `Capacity`, `Policy`. Vendor terms should exist as top level terms also, but in other repositories (e.g. drutiny/acquia-cloud, drutiny/acquia-sitefactory).

**Comment by seanhamlin** [comment]
The main thing I am trying to achieve with the folder structure (and namespace I suppose) is that you can easily find the check you are after without having to look in all the folders. Having vague terms like 'Drupal' won't really help. I guess we can work out what this list should look like.

Happy for the 'requirements' to be fulfilled by traits and interfaces, that makes sense. Categories can be in YAML too, again, makes sense.

**Comment by fiasco** [comment]
> you can easily find the check you are after without having to look in all the folders

Could this be solved by using check:list and providing more detail in the list to help find it?

**Comment by seanhamlin** [comment]
I think we can close this issue now. 2.x is now up.
